import type { LangCode } from '../types/language'

type UiKey =
  | 'appName'
  | 'tagline'
  | 'chooseTarget'
  | 'comingSoon'
  | 'back'
  | 'asLearner'
  | 'hearPronunciation'
  | 'correct'
  | 'wrong'
  | 'next'
  | 'score'
  | 'restart'
  | 'noMoreQuestions'
  | 'categories'
  | 'startCategory'
  | 'emptyCategory'
  | 'languageHubLead'
  | 'overview'
  | 'roundResult'
  | 'perfectRound'
  | 'retryMissed'
  | 'missedSummary'
  | 'yourAnswer'
  | 'correctAnswer'
  | 'tapToContinue'
  | 'openTable'
  | 'close'

const EN: Record<UiKey, string> = {
  appName: 'LangStart',
  tagline: 'First words. Every language.',
  chooseTarget: 'Pick a language to start',
  comingSoon: 'Coming soon',
  back: 'Back',
  asLearner: 'Your language',
  hearPronunciation: 'Pronunciation',
  correct: 'Correct!',
  wrong: 'Not quite',
  next: 'Next',
  score: 'Score',
  restart: 'Restart',
  noMoreQuestions: 'You finished this set!',
  categories: 'Categories',
  startCategory: 'Start quiz',
  emptyCategory: 'No cards in this category yet.',
  languageHubLead: 'Start with the basics — the must-memorize steps for beginners.',
  overview: 'Overview',
  roundResult: 'Round {n} results',
  perfectRound: 'Perfect — all correct!',
  retryMissed: 'Retry {n} missed',
  missedSummary: '{correct} correct · {missed} missed. Retry the ones you missed.',
  yourAnswer: 'You',
  correctAnswer: 'Answer',
  tapToContinue: 'Tap to continue',
  openTable: 'Table',
  close: 'Close',
}

export const UI_STRINGS: Record<LangCode, Partial<Record<UiKey, string>>> = {
  en: EN,
  ko: {
    appName: 'LangStart',
    tagline: '시작할 때 꼭 외울 것들.',
    chooseTarget: '배우고 싶은 언어를 고르세요',
    comingSoon: '준비 중',
    back: '뒤로',
    asLearner: '내 언어',
    hearPronunciation: '발음',
    correct: '정답!',
    wrong: '아쉬워요',
    next: '다음',
    score: '점수',
    restart: '다시 하기',
    noMoreQuestions: '이 세트를 모두 풀었어요!',
    categories: '카테고리',
    startCategory: '퀴즈 시작',
    emptyCategory: '아직 이 카테고리 카드가 없어요.',
    languageHubLead: '기초부터 시작하세요. 외우기 귀찮지만 꼭 필요한 목차입니다.',
    overview: '개요',
    roundResult: '{n}라운드 결과',
    perfectRound: '완벽해요. 전부 정답입니다!',
    retryMissed: '오답 {n}개 다시 풀기',
    missedSummary: '정답 {correct}개 · 오답 {missed}개. 틀린 문제만 다시 풉니다.',
    yourAnswer: '내 답',
    correctAnswer: '정답',
    tapToContinue: '탭해서 계속',
    openTable: '표',
    close: '닫기',
  },
  ja: {
    appName: 'LangStart',
    tagline: 'はじめに覚える、あの基礎。',
    chooseTarget: '学びたい言語を選んでください',
    comingSoon: '準備中',
    back: '戻る',
    asLearner: 'あなたの言語',
    hearPronunciation: '発音',
    correct: '正解！',
    wrong: '残念',
    next: '次へ',
    score: 'スコア',
    restart: 'もう一度',
    noMoreQuestions: 'このセットをクリアしました！',
    categories: 'カテゴリー',
    startCategory: 'クイズを始める',
    emptyCategory: 'このカテゴリーにはまだカードがありません。',
    languageHubLead: 'まず基礎から。覚えるのは面倒でも必須のメニューです。',
    overview: '概要',
    roundResult: '{n}ラウンドの結果',
    perfectRound: 'パーフェクト！全部正解です',
    retryMissed: '間違えた {n}問をもう一度',
    missedSummary: '正解 {correct} · 不正解 {missed}。間違えた問題だけもう一度。',
    yourAnswer: 'あなたの答え',
    correctAnswer: '正解',
    tapToContinue: 'タップして続く',
    openTable: '表',
    close: '閉じる',
  },
  zh: {
    appName: 'LangStart',
    tagline: '入门必背，少走弯路。',
    chooseTarget: '选择你想学习的语言',
    comingSoon: '即将推出',
    back: '返回',
    asLearner: '你的语言',
    hearPronunciation: '发音',
    correct: '正确！',
    wrong: '不对',
    next: '下一题',
    score: '得分',
    restart: '重新开始',
    noMoreQuestions: '本组已完成！',
    categories: '类别',
    startCategory: '开始测验',
    emptyCategory: '该类别还没有卡片。',
    languageHubLead: '从基础开始——初学者必背的入门内容。',
    overview: '概览',
    roundResult: '第 {n} 轮结果',
    perfectRound: '完美！全部正确',
    retryMissed: '重做 {n} 道错题',
    missedSummary: '正确 {correct} · 错误 {missed}。只重做错题。',
    yourAnswer: '你的答案',
    correctAnswer: '正确答案',
    tapToContinue: '点击继续',
    openTable: '对照表',
    close: '关闭',
  },
  fr: {
    appName: 'LangStart',
    tagline: 'Ce qu’il faut retenir pour bien commencer.',
    chooseTarget: 'Choisissez une langue à apprendre',
    comingSoon: 'Bientôt',
    back: 'Retour',
    asLearner: 'Votre langue',
    hearPronunciation: 'Prononciation',
    correct: 'Correct !',
    wrong: 'Pas tout à fait',
    next: 'Suivant',
    score: 'Score',
    restart: 'Recommencer',
    noMoreQuestions: 'Vous avez terminé ce set !',
    categories: 'Catégories',
    startCategory: 'Commencer le quiz',
    emptyCategory: 'Pas encore de cartes dans cette catégorie.',
    languageHubLead: 'Commencez par les bases — l’essentiel à mémoriser.',
    overview: 'Aperçu',
    roundResult: 'Résultat du tour {n}',
    perfectRound: 'Parfait — tout est correct !',
    retryMissed: 'Réessayer {n} erreurs',
    missedSummary: '{correct} correct(s) · {missed} erreur(s). Reprenez les ratés.',
    yourAnswer: 'Vous',
    correctAnswer: 'Réponse',
    tapToContinue: 'Touchez pour continuer',
    openTable: 'Tableau',
    close: 'Fermer',
  },
  es: {
    appName: 'LangStart',
    tagline: 'Lo esencial para arrancar bien.',
    chooseTarget: 'Elige un idioma para aprender',
    comingSoon: 'Próximamente',
    back: 'Atrás',
    asLearner: 'Tu idioma',
    hearPronunciation: 'Pronunciación',
    correct: '¡Correcto!',
    wrong: 'Casi',
    next: 'Siguiente',
    score: 'Puntos',
    restart: 'Reiniciar',
    noMoreQuestions: '¡Terminaste este set!',
    categories: 'Categorías',
    startCategory: 'Empezar quiz',
    emptyCategory: 'Aún no hay tarjetas en esta categoría.',
    languageHubLead: 'Empieza por lo básico — lo esencial que hay que memorizar.',
    overview: 'Resumen',
    roundResult: 'Resultados de la ronda {n}',
    perfectRound: '¡Perfecto — todo correcto!',
    retryMissed: 'Repetir {n} fallos',
    missedSummary: '{correct} correctas · {missed} fallos. Solo los fallos otra vez.',
    yourAnswer: 'Tú',
    correctAnswer: 'Respuesta',
    tapToContinue: 'Toca para continuar',
    openTable: 'Tabla',
    close: 'Cerrar',
  },
  de: {
    appName: 'LangStart',
    tagline: 'Was man zum Start einfach können muss.',
    chooseTarget: 'Wähle eine Sprache zum Lernen',
    comingSoon: 'Demnächst',
    back: 'Zurück',
    asLearner: 'Deine Sprache',
    hearPronunciation: 'Aussprache',
    correct: 'Richtig!',
    wrong: 'Leider falsch',
    next: 'Weiter',
    score: 'Punkte',
    restart: 'Neu starten',
    noMoreQuestions: 'Dieses Set ist fertig!',
    categories: 'Kategorien',
    startCategory: 'Quiz starten',
    emptyCategory: 'In dieser Kategorie gibt es noch keine Karten.',
    languageHubLead: 'Fang mit den Grundlagen an — das, was man auswendig brauchen wird.',
    overview: 'Übersicht',
    roundResult: 'Runde-{n}-Ergebnis',
    perfectRound: 'Perfekt — alles richtig!',
    retryMissed: '{n} Fehler wiederholen',
    missedSummary: '{correct} richtig · {missed} falsch. Nur die Fehler noch einmal.',
    yourAnswer: 'Du',
    correctAnswer: 'Antwort',
    tapToContinue: 'Tippen zum Weiter',
    openTable: 'Tabelle',
    close: 'Schließen',
  },
  ru: {
    appName: 'LangStart',
    tagline: 'То, что нужно выучить в самом начале.',
    chooseTarget: 'Выберите язык для изучения',
    comingSoon: 'Скоро',
    back: 'Назад',
    asLearner: 'Ваш язык',
    hearPronunciation: 'Произношение',
    correct: 'Верно!',
    wrong: 'Не совсем',
    next: 'Дальше',
    score: 'Счёт',
    restart: 'Заново',
    noMoreQuestions: 'Этот набор пройден!',
    categories: 'Категории',
    startCategory: 'Начать тест',
    emptyCategory: 'В этой категории пока нет карточек.',
    languageHubLead: 'Начните с основ — то, что скучно, но нужно запомнить.',
    overview: 'Обзор',
    roundResult: 'Итог раунда {n}',
    perfectRound: 'Идеально — всё верно!',
    retryMissed: 'Повторить {n} ошибок',
    missedSummary: '{correct} верно · {missed} ошибок. Только ошибки ещё раз.',
    yourAnswer: 'Вы',
    correctAnswer: 'Ответ',
    tapToContinue: 'Нажмите, чтобы продолжить',
    openTable: 'Таблица',
    close: 'Закрыть',
  },
}

export function t(learnerLang: LangCode, key: UiKey): string {
  return UI_STRINGS[learnerLang]?.[key] ?? UI_STRINGS.en[key] ?? key
}

/** Replace `{name}` placeholders in a UI string. */
export function tf(
  learnerLang: LangCode,
  key: UiKey,
  vars: Record<string, string | number>,
): string {
  return Object.entries(vars).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    t(learnerLang, key),
  )
}
